name: CI - Azure CR Build & Push

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    NAME: my-fastapi-app
    TAG: latest

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v4

            - name: Iniciar sesión en el registro de contenedores de Azure
              run: echo ${{ secrets.azurecr_password }} | docker login ${{ secrets.azurecr_uri }} -u ${{ secrets.azurecr_username }} --password-stdin

            - name: Contruir imagen de Docker
              run: docker build -t ${{ secrets.azurecr_uri }}/$NAME:$TAG .

            - name: Subir imagen de Docker
              run: docker push ${{ secrets.azurecr_uri }}/$NAME:$TAG