name: CI - Docker Build & Push

on:
    push:
        branches:
            - main

env:
    NAME: my-fastapi-app
    NAMESPACE: xxblackmasterxx
    ORG: ghcr.io
    TAG: latest

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v4

            - name: Iniciar sesión en el registro de contenedores de GitHub
              run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Contruir imagen de Docker
              run: docker build -t $ORG/$NAMESPACE/$NAME:$TAG .

            - name: Subir imagen de Docker
              run: docker push $ORG/$NAMESPACE/$NAME:$TAG